# This Dockerfile builds the API only.

FROM ubuntu:22.04
WORKDIR /app

RUN set -xe \
    && apt update \
    && apt install -y gcc python3-pip python3-dev git libsm6 libxext6 ffmpeg libfontconfig1 libxrender1 libgl1-mesa-glx

COPY api/requirements.txt ./
RUN pip install -r ./requirements.txt

COPY api/api.py api/image_processor.py api/.flaskenv api/swapper.py ./
