services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    image: alxgirard23/photomaiton-api:latest
    command: python3 /app/api.py --config /app/config.json
    runtime: nvidia
    deploy:
      resources:
        limits:
          memory: 16G
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ./config.json:/app/config.json
      - ./captures/:/app/captures/
      - /home/user/checkpoints/:/app/checkpoints/
      - /home/user/.cache/:/root/.cache/
      - /home/user/insightface/:/root/.insightface/
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    image: alxgirard23/photomaiton-client:latest
    volumes:
      - /home/user/ssl.crt:/app/certs/ssl.crt
      - /home/user/ssl.key:/app/certs/ssl.key
    ports:
      - "3000:443"
