services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    image: react-flask-sd-app-api
    volumes:
      - ./config.json:/app/api/config.json
      - ./captures/:/app/captures/
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    image: react-flask-sd-app-client
    ports:
      - "3000:80"
