services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    image: react-flask-sd-app-api
    command: python3 /app/api.py --config /app/config.json
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ./config.json:/app/config.json
      - ./captures/:/app/captures/
      - /home/user/checkpoints/:/app/checkpoints/
      - /home/user/.cache/:/root/.cache/
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    image: react-flask-sd-app-client
    volumes:
      - /home/user/ssl.crt:/app/certs/ssl.crt
      - /home/user/ssl.key:/app/certs/ssl.key
    ports:
      - "3000:443"
