services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    image: react-flask-sd-app-api
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ./config.json:/app/api/config.json
      - ./captures/:/app/captures/
      - /home/user/checkpoints/:/app/checkpoints/
      - /home/user/.cache/:/root/.cache/
    ports:
      - "5000:5000"
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    image: react-flask-sd-app-client
    ports:
      - "3000:80"
